### seed 설정
- 어떤 특정한 시작 숫자를 정해주면 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다.
- 이런 시작 숫자를 시드(seed)라 한다.
- 시드 값은 한 번만 정해 주면 된다.

In [1]:
import numpy as np

# 시드 설정 1)
np.random.seed(0)

In [2]:
# 시드 설정 2)

seed=0
np.random.seed(seed)

In [3]:
np.random.seed(0) # 0이 아니고 임의의 숫자만 넣어도 됨
np.random.rand(5) # 위 함수가 없으면 값이 계속 변경

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [4]:
np.random.seed(100)
np.random.rand(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [7]:
# 난수와 비슷하지만 시드 값에 따라 항상 같은 결과를 반환

np.random.seed(76923)

a = np.random.random((2,2))
b = np.random.sample((2,2))
c = np.random.randint(1, 3, (2,2), dtype=int)

print(a)
print()
print(b)
print()
print(c)

[[0.76367992 0.87641303]
 [0.53095238 0.38451373]]

[[0.2777934  0.05650517]
 [0.44143693 0.7142663 ]]

[[1 1]
 [2 1]]


### 난수 발생
- numpy의 random은 난수를 생성하는 다양한 명령을 제공
- 가장 간단하고 많이 사용되는 것
  - rand: 0~1 사이의 균일 분포, 실수 난수
  - randn: 가우시안 표준 정규분포, 실수 난수
  - randint: 균일분포의 정수난수

### 1) rand명령
- 0부터 1 사이의 균일한 확률 분포로 실수 난수를 생성
- 숫자 인수는 생성할 난수의 크기
- 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [8]:
np.random.rand(10)

array([0.89561778, 0.36096285, 0.63359909, 0.96328529, 0.85191882,
       0.38800361, 0.02801296, 0.13020714, 0.11466988, 0.58108648])

In [9]:
np.random.rand(3,5)

array([[0.19883419, 0.46556495, 0.93528704, 0.63436875, 0.99365433],
       [0.25872766, 0.60164293, 0.82295431, 0.3161916 , 0.58151487],
       [0.57874201, 0.94273135, 0.70971487, 0.59990189, 0.44133875]])

### 2) randn
- 기댓값이 0이고 표준편차가 1인 가우시안 표준 정규 분포를 따르는 난수를 생성

In [10]:
np.random.randn(5)

array([-0.88028354,  1.01727883, -1.22096014,  0.51734685, -0.22497505])

In [11]:
np.random.randn(10)

array([-0.41038002, -0.37562584, -0.69167121,  0.40994422, -0.81469928,
       -0.65947695, -0.83976835,  0.10899789, -0.35264968,  1.22099455])

In [12]:
np.random.randn(3,5)

array([[ 0.5431668 ,  1.71118221, -0.73653234, -0.03461925, -0.81263249],
       [ 0.39806962, -0.8376541 ,  0.45438589,  0.08730852,  0.69979765],
       [-0.33857362, -0.03746594, -1.31904969,  0.83602724, -1.04480596]])

### 3) randint
- randint(low, high=None, size=None)

In [13]:
np.random.randint(10, size=10)

array([2, 4, 0, 1, 4, 8, 1, 4, 9, 6])

In [14]:
np.random.randint(10, 20, size=10)

array([19, 12, 13, 11, 16, 17, 10, 19, 12, 19])

In [15]:
np.random.randint(10, 20, size=(3,5))

array([[12, 19, 18, 15, 12],
       [13, 11, 19, 18, 18],
       [18, 19, 15, 12, 17]])