In [2]:
from google.colab import drive
drive.mount("/content/gdrive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


### AND 게이트 구현

In [5]:
import numpy as np

def AND(x1, x2, w1 = 0.5, w2 = 0.5, b = -0.7):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y >= 0:
    return 1
  elif y < 0:
    return 0

In [6]:
print('AND(0,0) = ', AND(0,0))
print('AND(0,1) = ', AND(0,1))
print('AND(1,0) = ', AND(1,0))
print('AND(1,1) = ', AND(1,1))

AND(0,0) =  0
AND(0,1) =  0
AND(1,0) =  0
AND(1,1) =  1


### NAND 게이트 구현

In [7]:
import numpy as np

def NAND(x1, x2, w1 = -0.5, w2 = -0.5, b = 0.7):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y >= 0:
    return 1
  elif y < 0:
    return 0

In [10]:
print('NAND(0,0) = ', NAND(0,0))
print('NAND(0,1) = ', NAND(0,1))
print('NAND(1,0) = ', NAND(1,0))
print('NAND(1,1) = ', NAND(1,1))    # NAND 게이트는 AND 게이트의 부정 -> 결과 반대

NAND(0,0) =  1
NAND(0,1) =  1
NAND(1,0) =  1
NAND(1,1) =  0


### OR 게이트 구현

In [12]:
import numpy as np

def OR(x1, x2, w1 = 0.5, w2 = 0.5, b = -0.2):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y <= 0:
    return 0
  elif y > 0:
    return 1

In [13]:
print('OR(0,0) = ', OR(0,0))
print('OR(0,1) = ', OR(0,1))
print('OR(1,0) = ', OR(1,0))
print('OR(1,1) = ', OR(1,1))

OR(0,0) =  0
OR(0,1) =  1
OR(1,0) =  1
OR(1,1) =  1


### XOR 게이트 구현

In [14]:
def XOR(x1, x2):
  s1 = NAND(x1, x2)
  s2 = OR(x1, x2)
  y = AND(s1, s2)
  return y

In [15]:
print('XOR(0,0) = ', XOR(0,0))
print('XOR(0,1) = ', XOR(0,1))
print('XOR(1,0) = ', XOR(1,0))
print('XOR(1,1) = ', XOR(1,1))

XOR(0,0) =  0
XOR(0,1) =  1
XOR(1,0) =  1
XOR(1,1) =  0


### 다차원 배열의 계산

In [16]:
import numpy as np

A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [17]:
np.ndim(A)

1

In [18]:
A.shape

(4,)

In [19]:
A.shape[0]

4

In [21]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
np.ndim(B)

2

In [23]:
B.shape

(3, 2)

### 행렬의 내적

In [24]:
import numpy as np

A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [25]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [27]:
np.dot(A, B)  # 행렬의 내적(행렬 곱)

array([[19, 22],
       [43, 50]])

In [28]:
import numpy as np

A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [29]:
B = np.array([[7,8,9,10], [11,12,13,14]])
B.shape

(2, 4)

In [30]:
np.dot(A, B)  # 행렬의 내적(행렬 곱)

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

### 신경망의 내적

In [31]:
import numpy as np

X = np.array([1,2])
X.shape

(2,)

In [32]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [33]:
W.shape

(2, 3)

In [35]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
