In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


### AND 게이트 구현

In [ ]:
import numpy as np

def AND(x1, x2, w1 = 0.5, w2 = 0.5, b = -0.7):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y >= 0:
    return 1
  elif y < 0:
    return 0

In [ ]:
print('AND(0,0) = ', AND(0,0))
print('AND(0,1) = ', AND(0,1))
print('AND(1,0) = ', AND(1,0))
print('AND(1,1) = ', AND(1,1))

AND(0,0) =  0
AND(0,1) =  0
AND(1,0) =  0
AND(1,1) =  1


### NAND 게이트 구현

In [ ]:
import numpy as np

def NAND(x1, x2, w1 = -0.5, w2 = -0.5, b = 0.7):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y >= 0:
    return 1
  elif y < 0:
    return 0

In [ ]:
print('NAND(0,0) = ', NAND(0,0))
print('NAND(0,1) = ', NAND(0,1))
print('NAND(1,0) = ', NAND(1,0))
print('NAND(1,1) = ', NAND(1,1))    # NAND 게이트는 AND 게이트의 부정 -> 결과 반대

NAND(0,0) =  1
NAND(0,1) =  1
NAND(1,0) =  1
NAND(1,1) =  0


### OR 게이트 구현

In [ ]:
import numpy as np

def OR(x1, x2, w1 = 0.5, w2 = 0.5, b = -0.2):
  x = np.array([x1, x2])
  w = np.array([w1, w2])
  y = np.sum(x * w) + b
  
  if y <= 0:
    return 0
  elif y > 0:
    return 1

In [ ]:
print('OR(0,0) = ', OR(0,0))
print('OR(0,1) = ', OR(0,1))
print('OR(1,0) = ', OR(1,0))
print('OR(1,1) = ', OR(1,1))

OR(0,0) =  0
OR(0,1) =  1
OR(1,0) =  1
OR(1,1) =  1


### XOR 게이트 구현

In [ ]:
def XOR(x1, x2):
  s1 = NAND(x1, x2)
  s2 = OR(x1, x2)
  y = AND(s1, s2)
  return y

In [ ]:
print('XOR(0,0) = ', XOR(0,0))
print('XOR(0,1) = ', XOR(0,1))
print('XOR(1,0) = ', XOR(1,0))
print('XOR(1,1) = ', XOR(1,1))

XOR(0,0) =  0
XOR(0,1) =  1
XOR(1,0) =  1
XOR(1,1) =  0


### 다차원 배열의 계산

In [ ]:
import numpy as np

A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [ ]:
np.ndim(A)

1

In [ ]:
A.shape

(4,)

In [ ]:
A.shape[0]

4

In [ ]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.ndim(B)

2

In [ ]:
B.shape

(3, 2)

### 행렬의 내적

In [ ]:
import numpy as np

A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [ ]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [ ]:
np.dot(A, B)  # 행렬의 내적(행렬 곱)

array([[19, 22],
       [43, 50]])

In [ ]:
import numpy as np

A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [ ]:
B = np.array([[7,8,9,10], [11,12,13,14]])
B.shape

(2, 4)

In [ ]:
np.dot(A, B)  # 행렬의 내적(행렬 곱)

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

### 신경망의 내적

In [ ]:
import numpy as np

X = np.array([1,2])
X.shape

(2,)

In [ ]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [ ]:
W.shape

(2, 3)

In [ ]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


### 다층 퍼셉트론의 설계

In [36]:
import numpy as np

In [37]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [42]:
# 입력층에서 1층으로 신호 전달

In [38]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.5]])
B1 = np.array([0.1, 0.2, 0.3])

In [39]:
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [40]:
A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)

In [41]:
print(A1)
print(Z1)

[0.3  0.7  1.05]
[0.57444252 0.66818777 0.7407749 ]


In [43]:
# 1층에서 2층으로 신호 전달

In [44]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [45]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [46]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [47]:
print(A2)
print(Z2)

[0.51331428 1.20833583]
[0.6255831  0.77000436]


In [48]:
# 2층에서 출력층으로 신호 전달

In [49]:
def identify_function(x):
  return x

In [50]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [51]:
A3 = np.dot(Z2, W3) + B3
Y = identify_function(A3)

In [52]:
print(Y)

[0.31655918 0.69567667]


### 코딩으로 XOR 문제 해결하기

In [62]:
import numpy as np

# 가중치와 바이어스

w11 = np.array([-2, -2])
w12 = np.array([2, 2])
w2 = np.array([1, 1])
b1 = 3
b2 = -1
b3 = -1

In [63]:
# 퍼셉트론
def MLP(x, w, b):   # MLP(Multi Layer Perceptron)
  y = np.sum(w * x) + b
  if y <= 0:
    return 0
  else:
    return 1

# NAND gate
def NAND(x1, x2):
  return MLP(np.array([x1, x2]), w11, b1)

# OR gate
def OR(x1, x2):
  return MLP(np.array([x1, x2]), w12, b2)

# AND gate
def AND(x1, x2):
  return MLP(np.array([x1, x2]), w2, b3)

# XOR gate
def XOR(x1, x2):
  return AND(NAND(x1, x2), OR(x1, x2))

In [64]:
# x1, x2 값을 번갈아 대입해 가며 최종값 출력

if __name__ == '__main__':
  for x in [(0,0), (1,0), (0,1), (1,1)]:
    y = XOR(x[0], x[1])
    print("입력 값: " + str(x) + " 출력 값: " + str(y))

입력 값: (0, 0) 출력 값: 0
입력 값: (1, 0) 출력 값: 1
입력 값: (0, 1) 출력 값: 1
입력 값: (1, 1) 출력 값: 0
